// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Business.EntityFrameworkCore;

namespace Business.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200818071307_202008181512")]
    partial class _202008181512
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Business.Domain.Entities.AutoRepairStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AutoRepairStation");
                });

            modelBuilder.Entity("Business.Domain.Entities.BAH_MOProcessFlow", b =>
                {
                    b.Property<string>("bah_c031")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("bah_c12")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("bah_c02")
                        .HasColumnType("int");

                    b.Property<int>("bah_c03")
                        .HasColumnType("int");

                    b.Property<string>("bah_c04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bah_c05")
                        .HasColumnType("int");

                    b.Property<int>("bah_c06")
                        .HasColumnType("int");

                    b.Property<string>("bah_c07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_c08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_c09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_c10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_c13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_c14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_cConfirmUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_cCreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_cCustID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_cLastUpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("bah_cMinTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("bah_cState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("bah_cTimeoutControl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("bah_cValid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_cdescribe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("bah_dConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("bah_dCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("bah_dLastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("bah_n11")
                        .HasColumnType("int");

                    b.Property<int>("bah_n12")
                        .HasColumnType("int");

                    b.Property<string>("bah_nConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bah_nEdition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bah_c031", "bah_c12");

                    b.ToTable("BAH_MOProcessFlow");
                });

            modelBuilder.Entity("Business.Domain.Entities.BAJ_MO", b =>
                {
                    b.Property<string>("baj_c02")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c100")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c101")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c102")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c103")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c104")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c105")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c106")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c107")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c108")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c109")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c110")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c111")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c112")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c113")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c114")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c115")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c116")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c117")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c118")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c119")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c120")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c121")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c122")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c123")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c124")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c125")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c126")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c127")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c128")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c129")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c130")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c131")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c132")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c133")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c134")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c135")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c34")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c35")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c36")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c37")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c38")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c39")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c41")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c42")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c43")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c44")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c45")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c46")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c47")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c48")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c49")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c51")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c52")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c53")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c54")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c57")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c58")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c59")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c60")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c61")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c62")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c63")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c65")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c66")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c68")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c71")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c72")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c73")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c78")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c79")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c80")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c81")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c82")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c83")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c84")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c85")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c86")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c87")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c88")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c89")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c90")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c91")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c92")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c93")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c94")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c95")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c96")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c97")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c98")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_c99")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cAUART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cAUFNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cColorA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cColorB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cColorC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cColorD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cFTRMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cKDMAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cMAKTX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cMATKL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cPLNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cPN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cUPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cWERKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZPROJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZP_CUSTOMER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZP_KH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZP_KH_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZRWL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZRWLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZZBOMV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZZLINE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZZRWLENUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_cZZRWLNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("baj_n01")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n25")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n55")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n56")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n67")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n69")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n70")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n74")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n75")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n76")
                        .HasColumnType("int");

                    b.Property<int?>("baj_n77")
                        .HasColumnType("int");

                    b.Property<string>("baj_nFactoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baj_nVersionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diy_theme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("baj_c02");

                    b.ToTable("BAJ_MO");
                });

            modelBuilder.Entity("Business.Domain.Entities.C_WORK_DESC_T", b =>
                {
                    b.Property<string>("LINE_NAME")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SECTION_NAME")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WORK_SECTION")
                        .HasColumnType("int");

                    b.Property<string>("END_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SHIFT")
                        .HasColumnType("int");

                    b.Property<string>("START_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TARGET")
                        .HasColumnType("int");

                    b.HasKey("LINE_NAME", "SECTION_NAME", "WORK_SECTION");

                    b.ToTable("C_WORK_DESC_T");
                });

            modelBuilder.Entity("Business.Domain.Entities.ConsumeDetailTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsumeType")
                        .HasColumnType("int");

                    b.Property<int>("PeopleTestId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PeopleTestId")
                        .IsUnique();

                    b.ToTable("ConsumeDetailTests");
                });

            modelBuilder.Entity("Business.Domain.Entities.CourseTest3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourseTest3");
                });

            modelBuilder.Entity("Business.Domain.Entities.DeveloperTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Followers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DeveloperTests");
                });

            modelBuilder.Entity("Business.Domain.Entities.GradeTest2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GradeTest2s");
                });

            modelBuilder.Entity("Business.Domain.Entities.PeopleTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IDNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PeopleTests");
                });

            modelBuilder.Entity("Business.Domain.Entities.R_STATION_REC_T", b =>
                {
                    b.Property<string>("BIGFLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPUTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ECN_FAIL_QTY")
                        .HasColumnType("int");

                    b.Property<int?>("ECN_PASS_QTY")
                        .HasColumnType("int");

                    b.Property<int?>("FAIL_QTY")
                        .HasColumnType("int");

                    b.Property<string>("GROUP_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LAST_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LINE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODEL_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MO_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PASS_QTY")
                        .HasColumnType("int");

                    b.Property<string>("QmesSend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QmesSuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("REFAIL_QTY")
                        .HasColumnType("int");

                    b.Property<int?>("REPASS_QTY")
                        .HasColumnType("int");

                    b.Property<string>("SECTION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIDEFLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WIP_QTY")
                        .HasColumnType("int");

                    b.Property<string>("WORK_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WORK_SECTION")
                        .HasColumnType("int");

                    b.Property<string>("WO_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("R_STATION_REC_T");
                });

            modelBuilder.Entity("Business.Domain.Entities.R_WIP_TRACKING_T", b =>
                {
                    b.Property<string>("SERIAL_NUMBER")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CARTON_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CR_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMER_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMER_SW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERROR_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FINISH_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRADE_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GROUP_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOLD_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOLD_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IN_LINE_TIME")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IN_STATION_TIME")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KEY_PART_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LINE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCK_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODEL_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MO_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NEXT_STATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OUT_LINE_TIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("PALLET_FULL_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PALLET_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QA_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QA_RESULT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("REPAIR_CNT")
                        .HasColumnType("int");

                    b.Property<string>("REWORK_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMA_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCRAP_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECTION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SHIPPING_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("SHIPPING_SN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHIP_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMT_PART_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SN_LINE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SN_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPECIAL_ROUTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("STATION_SEQ")
                        .HasColumnType("int");

                    b.Property<string>("STATUS_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SW_BOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERSION_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WARRANTY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("WATERPROOF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WORK_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SERIAL_NUMBER");

                    b.ToTable("R_WIP_TRACKING_T");
                });

            modelBuilder.Entity("Business.Domain.Entities.Rawdata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DATA_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERROR_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERROR_DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GROUP_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IN_STATION_TIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("LINE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODEL_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MO_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REPAIRER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REPAIR_KEYPART_INFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REPAIR_REASON_INFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REPAIR_RESULT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RETRY_EC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SERIAL_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEST_RESULT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rawdata");
                });

            modelBuilder.Entity("Business.Domain.Entities.StationResume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("testTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("testType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testWorkID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testWorkorder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StationResume");
                });

            modelBuilder.Entity("Business.Domain.Entities.StationResume_Fail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testRec5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("testTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("testType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testWorkID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testWorkorder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StationResume_Fail");
                });

            modelBuilder.Entity("Business.Domain.Entities.Station_information", b =>
                {
                    b.Property<string>("wtuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BigSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C100")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C101")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C102")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C103")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C104")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C105")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C106")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C107")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C108")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C109")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C110")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C111")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C112")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C113")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C114")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C115")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C116")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C117")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C118")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C119")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C120")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C121")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C122")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C123")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C124")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C125")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C126")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C127")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C128")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C129")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C130")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C131")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C132")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C133")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C134")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C135")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C136")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C137")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C138")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C139")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C140")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C141")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C142")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C143")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C144")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C145")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C146")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C147")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C148")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C149")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C150")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C151")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C152")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C153")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C154")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C155")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C156")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C157")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C158")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C159")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C160")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C161")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C162")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C163")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C164")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C165")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C166")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C167")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C168")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C169")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C170")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C171")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C172")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C173")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C174")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C175")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C176")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C177")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C178")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C179")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C180")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C181")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C182")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C183")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C184")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C185")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C186")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C187")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C188")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C189")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C190")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C191")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C192")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C193")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C194")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C195")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C196")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C197")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C198")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C199")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C200")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C201")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C202")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C203")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C204")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C205")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C206")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C207")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C208")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C209")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C210")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C211")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C212")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C213")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C214")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C215")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C216")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C217")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C218")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C219")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C220")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C221")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C222")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C223")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C224")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C225")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C226")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C227")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C228")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C229")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C230")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C231")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C232")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C233")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C234")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C235")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C236")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C237")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C238")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C239")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C240")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C241")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C242")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C243")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C244")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C245")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C246")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C247")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C248")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C249")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C250")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C34")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C35")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C36")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C37")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C38")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C39")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C41")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C42")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C43")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C44")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C45")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C46")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C47")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C48")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C49")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C51")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C52")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C53")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C54")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C55")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C56")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C57")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C58")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C59")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C60")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C61")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C62")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C63")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C65")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C66")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C67")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C68")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C69")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C70")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C71")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C72")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C73")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C74")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C75")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C76")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C77")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C78")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C79")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C80")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C81")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C82")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C83")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C84")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C85")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C86")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C87")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C88")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C89")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C90")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C91")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C92")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C93")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C94")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C95")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C96")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C97")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C98")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C99")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessFlow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PtintTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RE")
                        .HasColumnType("int");

                    b.Property<int>("RR")
                        .HasColumnType("int");

                    b.Property<int>("RW")
                        .HasColumnType("int");

                    b.Property<string>("SN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("stime")
                        .HasColumnType("datetime2");

                    b.HasKey("wtuid");

                    b.ToTable("Station_information");
                });

            modelBuilder.Entity("Business.Domain.Entities.StudentCourse3", b =>
                {
                    b.Property<int>("StudentTest3Id")
                        .HasColumnType("int");

                    b.Property<int>("CourseTest3Id")
                        .HasColumnType("int");

                    b.HasKey("StudentTest3Id", "CourseTest3Id");

                    b.HasIndex("CourseTest3Id");

                    b.ToTable("StudentCourse3");
                });

            modelBuilder.Entity("Business.Domain.Entities.StudentTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("StudentTests");
                });

            modelBuilder.Entity("Business.Domain.Entities.StudentTest2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GradeTest2Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeTest2Id");

                    b.ToTable("StudentTest2s");
                });

            modelBuilder.Entity("Business.Domain.Entities.StudentTest3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentTest3");
                });

            modelBuilder.Entity("Business.Domain.Entities.WriteNumber", b =>
                {
                    b.Property<string>("PcbSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BtMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomizeSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FpOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FpSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID2")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IMEIWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imei_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imei_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imei_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imei_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MEID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PcbSNWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Wifi2Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wifi3Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wifi4Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WifiMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WriteIMEIAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WritePcbSNAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PcbSN");

                    b.ToTable("WriteNumber");
                });

            modelBuilder.Entity("Business.Domain.Entities.ConsumeDetailTest", b =>
                {
                    b.HasOne("Business.Domain.Entities.PeopleTest", "PeopleTest")
                        .WithOne("ConsumeDetailTest")
                        .HasForeignKey("Business.Domain.Entities.ConsumeDetailTest", "PeopleTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Business.Domain.Entities.StudentCourse3", b =>
                {
                    b.HasOne("Business.Domain.Entities.CourseTest3", "CourseTest3")
                        .WithMany("StudentCourse3s")
                        .HasForeignKey("CourseTest3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Domain.Entities.StudentTest3", "StudentTest3")
                        .WithMany("StudentCourse3s")
                        .HasForeignKey("StudentTest3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Business.Domain.Entities.StudentTest2", b =>
                {
                    b.HasOne("Business.Domain.Entities.GradeTest2", "GradeTest2")
                        .WithMany("StudentTest2s")
                        .HasForeignKey("GradeTest2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
