using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Common.Domain.Entities;

namespace Business.Domain.Entities
{
    public class BAJ_MO : IEntity
    {
        public int baj_n01 { get; set; }
        [Key]
        public string baj_c02 { get; set; }
        public string baj_c03 { get; set; }
        public string baj_c04 { get; set; }
        public string baj_c05 { get; set; }
        public string baj_c06 { get; set; }
        public string baj_c07 { get; set; }
        public string baj_c08 { get; set; }
        public string baj_c09 { get; set; }
        public string baj_c10 { get; set; }
        public string baj_c11 { get; set; }
        public string baj_c12 { get; set; }
        public string baj_c13 { get; set; }
        public string baj_c14 { get; set; }
        public string baj_c15 { get; set; }
        public string baj_c16 { get; set; }
        public string baj_c17 { get; set; }
        public string baj_c18 { get; set; }
        public string baj_c19 { get; set; }
        public string baj_c20 { get; set; }
        public string baj_c21 { get; set; }
        public string baj_c22 { get; set; }
        public string baj_c23 { get; set; }
        public string baj_c24 { get; set; }
        public Nullable<int> baj_n25 { get; set; }
        public string baj_c26 { get; set; }
        public string baj_c27 { get; set; }
        public string baj_c28 { get; set; }
        public string baj_c29 { get; set; }
        public string baj_c30 { get; set; }
        public string baj_c31 { get; set; }
        public string baj_c32 { get; set; }
        public string baj_c33 { get; set; }
        public string baj_c34 { get; set; }
        public string baj_c35 { get; set; }
        public string baj_c36 { get; set; }
        public string baj_c37 { get; set; }
        public string baj_c38 { get; set; }
        public string baj_c39 { get; set; }
        public string baj_c40 { get; set; }
        public string baj_c41 { get; set; }
        public string baj_c42 { get; set; }
        public string baj_c43 { get; set; }
        public string baj_c44 { get; set; }
        public string baj_c45 { get; set; }
        public string baj_c46 { get; set; }
        public string baj_c47 { get; set; }
        public string baj_c48 { get; set; }
        public string baj_c49 { get; set; }
        public string baj_c50 { get; set; }
        public string baj_c51 { get; set; }
        public string baj_c52 { get; set; }
        public string baj_c53 { get; set; }
        public string baj_c54 { get; set; }
        public Nullable<int> baj_n55 { get; set; }
        public Nullable<int> baj_n56 { get; set; }
        public string baj_c57 { get; set; }
        public string baj_c58 { get; set; }
        public string baj_c59 { get; set; }
        public string baj_c60 { get; set; }
        public string baj_c61 { get; set; }
        public string baj_c62 { get; set; }
        public string baj_c63 { get; set; }
        public string baj_c64 { get; set; }
        public string baj_c65 { get; set; }
        public string baj_c66 { get; set; }
        public Nullable<int> baj_n67 { get; set; }
        public string baj_c68 { get; set; }
        public Nullable<int> baj_n69 { get; set; }
        public Nullable<int> baj_n70 { get; set; }
        public string baj_c71 { get; set; }
        public string baj_c72 { get; set; }
        public string baj_c73 { get; set; }
        public Nullable<int> baj_n74 { get; set; }
        public Nullable<int> baj_n75 { get; set; }
        public Nullable<int> baj_n76 { get; set; }
        public Nullable<int> baj_n77 { get; set; }
        public string baj_c78 { get; set; }
        public string baj_c79 { get; set; }
        public string baj_c80 { get; set; }
        public string baj_c81 { get; set; }
        public string baj_c82 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUserId { get; set; }
        public string CompanyId { get; set; }
        public string BuId { get; set; }
        public string DeptId { get; set; }
        public string GroupId { get; set; }
        public string CreateUserName { get; set; }
        public string UpdateUserName { get; set; }
        public string baj_cAUFNR { get; set; }
        public string baj_cPLNUM { get; set; }
        public string baj_cWERKS { get; set; }
        public string baj_cAUART { get; set; }
        public string baj_cMAKTX { get; set; }
        public string baj_cZPROJ { get; set; }
        public string baj_cMATKL { get; set; }
        public string baj_cFTRMI { get; set; }
        public string baj_cZZBOMV { get; set; }
        public string baj_cKDMAT { get; set; }
        public string baj_cZP_KH { get; set; }
        public string baj_cZZLINE { get; set; }
        public string baj_nVersionName { get; set; }
        public string baj_cColorA { get; set; }
        public string baj_cColorB { get; set; }
        public string baj_cColorC { get; set; }
        public string baj_cUPC { get; set; }
        public string baj_nFactoryCode { get; set; }
        public string baj_cPN { get; set; }
        public string baj_cZRWL { get; set; }
        public string baj_cZRWLE { get; set; }
        public string baj_cZZRWLNUM { get; set; }
        public string baj_cZZRWLENUM { get; set; }
        public string diy_theme { get; set; }
        public string baj_cColorD { get; set; }
        public string baj_cZP_KH_TYPE { get; set; }
        public string baj_cZP_CUSTOMER { get; set; }
        public string baj_c83 { get; set; }
        public string baj_c84 { get; set; }
        public string baj_c85 { get; set; }
        public string baj_c86 { get; set; }
        public string baj_c87 { get; set; }
        public string baj_c88 { get; set; }
        public string baj_c89 { get; set; }
        public string baj_c90 { get; set; }
        public string baj_c91 { get; set; }
        public string baj_c92 { get; set; }
        public string baj_c93 { get; set; }
        public string baj_c94 { get; set; }
        public string baj_c95 { get; set; }
        public string baj_c96 { get; set; }
        public string baj_c97 { get; set; }
        public string baj_c98 { get; set; }
        public string baj_c99 { get; set; }
        public string baj_c100 { get; set; }
        public string baj_c101 { get; set; }
        public string baj_c102 { get; set; }
        public string baj_c103 { get; set; }
        public string baj_c104 { get; set; }
        public string baj_c105 { get; set; }
        public string baj_c106 { get; set; }
        public string baj_c107 { get; set; }
        public string baj_c108 { get; set; }
        public string baj_c109 { get; set; }
        public string baj_c110 { get; set; }
        public string baj_c111 { get; set; }
        public string baj_c112 { get; set; }
        public string baj_c113 { get; set; }
        public string baj_c114 { get; set; }
        public string baj_c115 { get; set; }
        public string baj_c116 { get; set; }
        public string baj_c117 { get; set; }
        public string baj_c118 { get; set; }
        public string baj_c119 { get; set; }
        public string baj_c120 { get; set; }
        public string baj_c121 { get; set; }
        public string baj_c122 { get; set; }
        public string baj_c123 { get; set; }
        public string baj_c124 { get; set; }
        public string baj_c125 { get; set; }
        public string baj_c126 { get; set; }
        public string baj_c127 { get; set; }
        public string baj_c128 { get; set; }
        public string baj_c129 { get; set; }
        public string baj_c130 { get; set; }
        public string baj_c131 { get; set; }
        public string baj_c132 { get; set; }
        public string baj_c133 { get; set; }
        public string baj_c134 { get; set; }
        public string baj_c135 { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    }
}
