using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Common.Domain.Entities;

namespace Business.Domain.Entities
{
    public class Station_information : IEntity
    {
        [Key]
        public string wtuid { get; set; }
        public Nullable<System.DateTime> stime { get; set; }
        public string ProcessFlow { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public string C8 { get; set; }
        public string C9 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public string C16 { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C19 { get; set; }
        public string C20 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string C25 { get; set; }
        public string C26 { get; set; }
        public string C27 { get; set; }
        public string C28 { get; set; }
        public string C29 { get; set; }
        public string C30 { get; set; }
        public string C31 { get; set; }
        public string C32 { get; set; }
        public string C33 { get; set; }
        public string C34 { get; set; }
        public string C35 { get; set; }
        public string C36 { get; set; }
        public string C37 { get; set; }
        public string C38 { get; set; }
        public string C39 { get; set; }
        public string C40 { get; set; }
        public string C41 { get; set; }
        public string C42 { get; set; }
        public string C43 { get; set; }
        public string C44 { get; set; }
        public string C45 { get; set; }
        public string C46 { get; set; }
        public string C47 { get; set; }
        public string C48 { get; set; }
        public string C49 { get; set; }
        public string C50 { get; set; }
        public string C51 { get; set; }
        public string C52 { get; set; }
        public string C53 { get; set; }
        public string C54 { get; set; }
        public string C55 { get; set; }
        public string C56 { get; set; }
        public string C57 { get; set; }
        public string C58 { get; set; }
        public string C59 { get; set; }
        public string C60 { get; set; }
        public string C61 { get; set; }
        public string C62 { get; set; }
        public string C63 { get; set; }
        public string C64 { get; set; }
        public string C65 { get; set; }
        public string C66 { get; set; }
        public string C67 { get; set; }
        public string C68 { get; set; }
        public string C69 { get; set; }
        public string C70 { get; set; }
        public string C71 { get; set; }
        public string C72 { get; set; }
        public string C73 { get; set; }
        public string C74 { get; set; }
        public string C75 { get; set; }
        public string C76 { get; set; }
        public string C77 { get; set; }
        public string C78 { get; set; }
        public string C79 { get; set; }
        public string C80 { get; set; }
        public string C81 { get; set; }
        public string C82 { get; set; }
        public string C83 { get; set; }
        public string C84 { get; set; }
        public string C85 { get; set; }
        public string C86 { get; set; }
        public string C87 { get; set; }
        public string C88 { get; set; }
        public string C89 { get; set; }
        public string C90 { get; set; }
        public string C91 { get; set; }
        public string C92 { get; set; }
        public string C93 { get; set; }
        public string C94 { get; set; }
        public string C95 { get; set; }
        public string C96 { get; set; }
        public string C97 { get; set; }
        public string C98 { get; set; }
        public string C99 { get; set; }
        public string C100 { get; set; }
        public string C101 { get; set; }
        public string C102 { get; set; }
        public string C103 { get; set; }
        public string C104 { get; set; }
        public string C105 { get; set; }
        public string C106 { get; set; }
        public string C107 { get; set; }
        public string C108 { get; set; }
        public string C109 { get; set; }
        public string C110 { get; set; }
        public string C111 { get; set; }
        public string C112 { get; set; }
        public string C113 { get; set; }
        public string C114 { get; set; }
        public string C115 { get; set; }
        public string C116 { get; set; }
        public string C117 { get; set; }
        public string C118 { get; set; }
        public string C119 { get; set; }
        public string C120 { get; set; }
        public string C121 { get; set; }
        public string C122 { get; set; }
        public string C123 { get; set; }
        public string C124 { get; set; }
        public string C125 { get; set; }
        public string C126 { get; set; }
        public string C127 { get; set; }
        public string C128 { get; set; }
        public string C129 { get; set; }
        public string C130 { get; set; }
        public string C131 { get; set; }
        public string C132 { get; set; }
        public string C133 { get; set; }
        public string C134 { get; set; }
        public string C135 { get; set; }
        public string C136 { get; set; }
        public string C137 { get; set; }
        public string C138 { get; set; }
        public string C139 { get; set; }
        public string Model { get; set; }
        public int RR { get; set; }
        public int RE { get; set; }
        public int RW { get; set; }
        public string PtintTime { get; set; }
        public string BigSN { get; set; }
        public string SN { get; set; }
        public string IMEI { get; set; }
        public string C140 { get; set; }
        public string C141 { get; set; }
        public string C142 { get; set; }
        public string C143 { get; set; }
        public string C144 { get; set; }
        public string C145 { get; set; }
        public string C146 { get; set; }
        public string C147 { get; set; }
        public string C148 { get; set; }
        public string C149 { get; set; }
        public string C150 { get; set; }
        public string C151 { get; set; }
        public string C152 { get; set; }
        public string C153 { get; set; }
        public string C154 { get; set; }
        public string C155 { get; set; }
        public string C156 { get; set; }
        public string C157 { get; set; }
        public string C158 { get; set; }
        public string C159 { get; set; }
        public string C160 { get; set; }
        public string C161 { get; set; }
        public string C162 { get; set; }
        public string C163 { get; set; }
        public string C164 { get; set; }
        public string C165 { get; set; }
        public string C166 { get; set; }
        public string C167 { get; set; }
        public string C168 { get; set; }
        public string C169 { get; set; }
        public string C170 { get; set; }
        public string C171 { get; set; }
        public string C172 { get; set; }
        public string C173 { get; set; }
        public string C174 { get; set; }
        public string C175 { get; set; }
        public string C176 { get; set; }
        public string C177 { get; set; }
        public string C178 { get; set; }
        public string C179 { get; set; }
        public string C180 { get; set; }
        public string C181 { get; set; }
        public string C182 { get; set; }
        public string C183 { get; set; }
        public string C184 { get; set; }
        public string C185 { get; set; }
        public string C186 { get; set; }
        public string C187 { get; set; }
        public string C188 { get; set; }
        public string C189 { get; set; }
        public string C190 { get; set; }
        public string C191 { get; set; }
        public string C192 { get; set; }
        public string C193 { get; set; }
        public string C194 { get; set; }
        public string C195 { get; set; }
        public string C196 { get; set; }
        public string C197 { get; set; }
        public string C198 { get; set; }
        public string C199 { get; set; }
        public string C200 { get; set; }
        public string C201 { get; set; }
        public string C202 { get; set; }
        public string C203 { get; set; }
        public string C204 { get; set; }
        public string C205 { get; set; }
        public string C206 { get; set; }
        public string C207 { get; set; }
        public string C208 { get; set; }
        public string C209 { get; set; }
        public string C210 { get; set; }
        public string C211 { get; set; }
        public string C212 { get; set; }
        public string C213 { get; set; }
        public string C214 { get; set; }
        public string C215 { get; set; }
        public string C216 { get; set; }
        public string C217 { get; set; }
        public string C218 { get; set; }
        public string C219 { get; set; }
        public string C220 { get; set; }
        public string C221 { get; set; }
        public string C222 { get; set; }
        public string C223 { get; set; }
        public string C224 { get; set; }
        public string C225 { get; set; }
        public string C226 { get; set; }
        public string C227 { get; set; }
        public string C228 { get; set; }
        public string C229 { get; set; }
        public string C230 { get; set; }
        public string C231 { get; set; }
        public string C232 { get; set; }
        public string C233 { get; set; }
        public string C234 { get; set; }
        public string C235 { get; set; }
        public string C236 { get; set; }
        public string C237 { get; set; }
        public string C238 { get; set; }
        public string C239 { get; set; }
        public string C240 { get; set; }
        public string C241 { get; set; }
        public string C242 { get; set; }
        public string C243 { get; set; }
        public string C244 { get; set; }
        public string C245 { get; set; }
        public string C246 { get; set; }
        public string C247 { get; set; }
        public string C248 { get; set; }
        public string C249 { get; set; }
        public string C250 { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    }
}
